export const ethnicities = [
  {value: 1, label: 'پښتون'},
  {value: 2, label: 'تاجک'},
  {value: 3, label: 'هزاره'},
  {value: 4, label: 'اوزبیک'},
  {value: 5, label: 'ترکمن'},
  {value: 6, label: 'بلوچ'},
  {value: 7, label: 'پشه یی'},
  {value: 8, label: 'ایماق'},
  {value: 9, label: 'نورستاني'},
  {value: 10, label: 'عرب'},
  {value: 11, label: 'قرغیز'},
  {value: 12, label: 'قزلباش'},
  {value: 13, label: 'گوجر'},
  {value: 14, label: 'براهوی'},
  {value: 15, label: 'اهل هنود'},
  {value: 16, label: 'سیکان'},
  {value: 17, label: 'سادات'},
  {value: 18, label: 'اورمړ'},
  {value: 19, label: 'پراچی'},
  {value: 20, label: 'کرد'},
  {value: 21, label: 'جوگی'},
  {value: 22, label: 'شاخیلان'},
  {value: 23, label: 'شیخ محمدروحانی'},
  {value: 24, label: 'گوار'},
  {value: 25, label: 'خلیلی'},
  {value: 26, label: 'پامیری'},
  {value: 27, label: 'منجانی'},
  {value: 28, label: 'سنگلیچی'},
  {value: 29, label: 'اشکاشمی'},
  {value: 30, label: 'روشنایی'},
  {value: 31, label: 'واخانی'},
  {value: 32, label: 'شغنانی'},
  {value: 33, label: 'ترک'},
  {value: 34, label: 'قرلق'},
  {value: 35, label: 'تاتار'},
  {value: 36, label: 'مغول'},
  {value: 37, label: 'ساکایی'},
  {value: 38, label: 'دولتخانی'},
  {value: 39, label: 'تایمنی'},
  {value: 40, label: 'البیگ'},
  {value: 41, label: 'قزاق'},
  {value: 42, label: 'سجانی'},
  {value: 43, label: 'غزنویان'},
  {value: 44, label: 'قوشخانیان'},
  {value: 45, label: 'بیات'},
  {value: 46, label: 'نیماق'},
  {value: 47, label: 'قبچاق'},
  {value: 48, label: 'نیکپی'},
  {value: 49, label: 'کهگداری'},
  {value: 50, label: 'دایمیرک'},
  {value: 51, label: 'میرسیده'},
  {value: 52, label: 'جمشیدیان'},
  {value: 53, label: 'افشاریان'},
  {value: 54, label: 'طاهریان'},
  {value: 55, label: 'سلجوقی'},
  {value: 56, label: 'تیموریان'},
  {value: 57, label: 'برلاس-ارلات'},
  {value: 58, label: 'ایلخانی'},
  {value: 59, label: 'یفتلی'},
  {value: 60, label: 'لقیان'},
  {value: 61, label: 'کاوی'},
  {value: 62, label: 'قوزی'},
  {value: 63, label: 'ابکه'},
  {value: 64, label: 'جغتایی'},
  {value: 65, label: 'گره‌یی'},
  {value: 66, label: 'کرمعلی'},
  {value: 67, label: 'شیخعلی'},
  {value: 68, label: 'اورتهبلاقی'},
  {value: 69, label: 'اویغور'},
  {value: 70, label: 'بابریان'},
  {value: 71, label: 'فرملی'},
]

export const religion = [
  {value: 1, label: 'اسلام'},
  {value: 2, label: 'هندو'},
  {value: 3, label: 'سیک'},
  {value: 4, label: 'عیسوی'},
  {value: 5, label: 'یهودی'},
  {value: 6, label: 'بودایی'},
]
export const language = [
  {value: 1, label: 'پشتو'},
  {value: 2, label: 'دری'},
  {value: 3, label: 'اوزبیکی'},
  {value: 4, label: 'ترکمنی'},
  {value: 5, label: 'بلوچی'},
  {value: 6, label: 'نورستانی'},
]

export const sects = [
  {value: 1, label: 'سنی'},
  {value: 2, label: 'شعیه'},
  {value: 3, label: 'دیگر'},
]
