export const provinces = [
  {value: 1, label: 'کابل'},
  {value: 2, label: 'کاپيسا'},
  {value: 3, label: 'پروان'},
  {value: 4, label: 'وردک'},
  {value: 5, label: 'لوگر'},
  {value: 6, label: 'ننگرهار'},
  {value: 7, label: 'لغمان'},
  {value: 8, label: 'پنجشير'},
  {value: 9, label: 'بغلان'},
  {value: 10, label: 'باميان'},
  {value: 11, label: 'غزني'},
  {value: 12, label: 'پکتيکا'},
  {value: 13, label: 'پکتيا'},
  {value: 14, label: 'خوست'},
  {value: 15, label: 'کنرها'},
  {value: 16, label: 'نورستان'},
  {value: 17, label: 'بدخشان'},
  {value: 18, label: 'تخار'},
  {value: 19, label: 'کندوز'},
  {value: 20, label: 'سمنگان'},
  {value: 21, label: 'بلخ'},
  {value: 22, label: 'سرپل'},
  {value: 23, label: 'غور'},
  {value: 24, label: 'دايکندي'},
  {value: 25, label: 'اورزگان'},
  {value: 26, label: 'زابل'},
  {value: 27, label: 'کندهار'},
  {value: 28, label: 'جوزجان'},
  {value: 29, label: 'فارياب'},
  {value: 30, label: 'هــلـمــند'},
  {value: 31, label: 'بادغيس'},
  {value: 32, label: 'هرات'},
  {value: 33, label: 'فراه'},
  {value: 34, label: 'نيمروز'},
]

export const districts = [
  {
    value: 1,
    label: 'چهارآسياب',
    district_pa: 'چهارآسياب',
    districtcode: '0103',
    provincecode: 1,
  },
  {value: 2, label: 'بگرامي', district_pa: 'بگرامي', districtcode: '0104', provincecode: 1},
  {value: 3, label: 'ده سبز', district_pa: 'ده سبز', districtcode: '0105', provincecode: 1},
  {value: 4, label: 'شکردره', district_pa: 'شکردره', districtcode: '0106', provincecode: 1},
  {value: 5, label: 'موسئي', district_pa: 'موسئي', districtcode: '0107', provincecode: 1},
  {
    value: 6,
    label: 'مير بچه کوت',
    district_pa: 'مير بچه کوت',
    districtcode: '0108',
    provincecode: 1,
  },
  {value: 7, label: 'خاک جبار', district_pa: 'خاک جبار', districtcode: '0109', provincecode: 1},
  {value: 8, label: 'کلکان', district_pa: 'کلکان', districtcode: '0110', provincecode: 1},
  {value: 9, label: 'گلدره', district_pa: 'گلدره', districtcode: '0111', provincecode: 1},
  {value: 10, label: 'فرزه', district_pa: 'فرزه', districtcode: '0112', provincecode: 1},
  {value: 11, label: 'استالف', district_pa: 'استالف', districtcode: '0113', provincecode: 1},
  {value: 12, label: 'قره باغ', district_pa: 'قره باغ', districtcode: '0114', provincecode: 1},
  {value: 13, label: 'سروبي', district_pa: 'سروبي', districtcode: '0115', provincecode: 1},
  {
    value: 14,
    label: 'محمود راقي',
    district_pa: 'محمود راقي',
    districtcode: '0201',
    provincecode: 2,
  },
  {
    value: 15,
    label: 'حصه دوم کوهستان',
    district_pa: 'حصه دوم کوهستان',
    districtcode: '0202',
    provincecode: 2,
  },
  {value: 16, label: 'کوه بند', district_pa: 'کوه بند', districtcode: '0203', provincecode: 2},
  {
    value: 17,
    label: 'حصه اول کوهستان',
    district_pa: 'حصه اول کوهستان',
    districtcode: '0204',
    provincecode: 2,
  },
  {value: 18, label: 'نجراب', district_pa: 'نجراب', districtcode: '0205', provincecode: 2},
  {value: 19, label: 'تگاب', district_pa: 'تگاب', districtcode: '0206', provincecode: 2},
  {value: 20, label: 'اله ساي', district_pa: 'اله ساي', districtcode: '0207', provincecode: 2},
  {
    value: 21,
    label: 'چاريکار',
    district_pa: 'چاريکار',
    districtcode: '0301',
    provincecode: 3,
  },
  {value: 22, label: 'بگرام', district_pa: 'بگرام', districtcode: '0302', provincecode: 3},
  {value: 23, label: 'شينواري', district_pa: 'شينواري', districtcode: '0303', provincecode: 3},
  {value: 24, label: 'سيد خيل', district_pa: 'سيد خيل', districtcode: '0304', provincecode: 3},
  {
    value: 25,
    label: 'جبل السراج',
    district_pa: 'جبل السراج',
    districtcode: '0305',
    provincecode: 3,
  },
  {value: 26, label: 'سالنگ', district_pa: 'سالنگ', districtcode: '0306', provincecode: 3},
  {
    value: 27,
    label: 'سياه گرد غوربند',
    district_pa: 'سياه گرد غوربند',
    districtcode: '0307',
    provincecode: 3,
  },
  {value: 28, label: 'کوه صافي', district_pa: 'کوه صافي', districtcode: '0308', provincecode: 3},
  {
    value: 29,
    label: 'سرخ پارسا',
    district_pa: 'سرخ پارسا',
    districtcode: '0309',
    provincecode: 3,
  },
  {value: 30, label: 'شيخ علي', district_pa: 'شيخ علي', districtcode: '0310', provincecode: 3},
  {
    value: 31,
    label: 'ميدان شهر',
    district_pa: 'ميدان شهر',
    districtcode: '0401',
    provincecode: 4,
  },
  {value: 32, label: 'نرخ', district_pa: 'نرخ', districtcode: '0402', provincecode: 4},
  {value: 33, label: 'جلريز', district_pa: 'جلريز', districtcode: '0403', provincecode: 4},
  {value: 34, label: 'چک وردک', district_pa: 'چک وردک', districtcode: '0404', provincecode: 4},
  {value: 35, label: 'سيد آباد', district_pa: 'سيد آباد', districtcode: '0405', provincecode: 4},
  {
    value: 36,
    label: 'دايميرداد',
    district_pa: 'دايميرداد',
    districtcode: '0406',
    provincecode: 4,
  },
  {
    value: 37,
    label: 'حصه اول بهسود',
    district_pa: 'حصه اول بهسود',
    districtcode: '0407',
    provincecode: 4,
  },
  {value: 38, label: 'جغتو', district_pa: 'جغتو', districtcode: '0408', provincecode: 4},
  {
    value: 39,
    label: 'مرکز بهسود',
    district_pa: 'مرکز بهسود',
    districtcode: '0409',
    provincecode: 4,
  },
  {
    value: 40,
    label: 'پل علم',
    district_pa: 'پل علم',
    districtcode: '0501',
    provincecode: 5,
  },
  {value: 41, label: 'برکي برک', district_pa: 'برکي برک', districtcode: '0502', provincecode: 5},
  {value: 42, label: 'چرخ', district_pa: 'چرخ', districtcode: '0503', provincecode: 5},
  {value: 43, label: 'خوشي', district_pa: 'خوشي', districtcode: '0504', provincecode: 5},
  {value: 44, label: 'محمد آغه', district_pa: 'محمد آغه', districtcode: '0505', provincecode: 5},
  {value: 45, label: 'خروار', district_pa: 'خروار', districtcode: '0506', provincecode: 5},
  {value: 46, label: 'ازره', district_pa: 'ازره', districtcode: '0507', provincecode: 5},
  {value: 47, label: 'بهسود', district_pa: 'بهسود', districtcode: '0602', provincecode: 6},
  {value: 48, label: 'سرخرود', district_pa: 'سرخرود', districtcode: '0603', provincecode: 6},
  {value: 49, label: 'چپرهار', district_pa: 'چپرهار', districtcode: '0604', provincecode: 6},
  {value: 50, label: 'کامه', district_pa: 'کامه', districtcode: '0605', provincecode: 6},
  {value: 51, label: 'کوزکنر', district_pa: 'کوزکنر', districtcode: '0606', provincecode: 6},
  {value: 52, label: 'رودات', district_pa: 'رودات', districtcode: '0607', provincecode: 6},
  {value: 53, label: 'خوگياني', district_pa: 'خوگياني', districtcode: '0608', provincecode: 6},
  {value: 54, label: 'بتي کوت', district_pa: 'بتي کوت', districtcode: '0609', provincecode: 6},
  {value: 55, label: 'ده بالا', district_pa: 'ده بالا', districtcode: '0610', provincecode: 6},
  {
    value: 56,
    label: 'پچيرواگام',
    district_pa: 'پچيرواگام',
    districtcode: '0611',
    provincecode: 6,
  },
  {value: 57, label: 'دره نور', district_pa: 'دره نور', districtcode: '0612', provincecode: 6},
  {value: 58, label: 'کوت', district_pa: 'کوت', districtcode: '0613', provincecode: 6},
  {value: 59, label: 'گوشته', district_pa: 'گوشته', districtcode: '0614', provincecode: 6},
  {value: 60, label: 'اچين', district_pa: 'اچين', districtcode: '0615', provincecode: 6},
  {value: 61, label: 'شينوار', district_pa: 'شينوار', districtcode: '0616', provincecode: 6},
  {value: 62, label: 'مهمنددره', district_pa: 'مهمنددره', districtcode: '0617', provincecode: 6},
  {value: 63, label: 'لعل پور', district_pa: 'لعل پور', districtcode: '0618', provincecode: 6},
  {value: 64, label: 'شيرزاد', district_pa: 'شيرزاد', districtcode: '0619', provincecode: 6},
  {value: 65, label: 'نازيان', district_pa: 'نازيان', districtcode: '0620', provincecode: 6},
  {value: 66, label: 'حصارک', district_pa: 'حصارک', districtcode: '0621', provincecode: 6},
  {value: 67, label: 'دربابا', district_pa: 'دربابا', districtcode: '0622', provincecode: 6},
  {
    value: 68,
    label: 'مهترلام',
    district_pa: 'مهترلام',
    districtcode: '0701',
    provincecode: 7,
  },
  {value: 69, label: 'قرغيي', district_pa: 'قرغيي', districtcode: '0702', provincecode: 7},
  {value: 70, label: 'عليشنگ', district_pa: 'عليشنگ', districtcode: '0703', provincecode: 7},
  {value: 71, label: 'علينگار', district_pa: 'علينگار', districtcode: '0704', provincecode: 7},
  {value: 72, label: 'دولت شاه', district_pa: 'دولت شاه', districtcode: '0705', provincecode: 7},
  {
    value: 73,
    label: 'بازارک',
    district_pa: 'بازارک',
    districtcode: '0801',
    provincecode: 8,
  },
  {value: 74, label: 'رخه', district_pa: 'رخه', districtcode: '0802', provincecode: 8},
  {value: 75, label: 'دره', district_pa: 'دره', districtcode: '0803', provincecode: 8},
  {
    value: 76,
    label: 'حصه اول - خنج',
    district_pa: 'حصه اول - خنج',
    districtcode: '0804',
    provincecode: 8,
  },
  {value: 77, label: 'عنابه', district_pa: 'عنابه', districtcode: '0805', provincecode: 8},
  {value: 78, label: 'شتل', district_pa: 'شتل', districtcode: '0806', provincecode: 8},
  {value: 79, label: 'پريان', district_pa: 'پريان', districtcode: '0807', provincecode: 8},
  {
    value: 80,
    label: 'پلخمري',
    district_pa: 'پلخمري',
    districtcode: '0901',
    provincecode: 9,
  },
  {
    value: 81,
    label: 'دهنه غوري',
    district_pa: 'دهنه غوري',
    districtcode: '0902',
    provincecode: 9,
  },
  {value: 82, label: 'دوشي', district_pa: 'دوشي', districtcode: '0903', provincecode: 9},
  {value: 83, label: 'نهرين', district_pa: 'نهرين', districtcode: '0904', provincecode: 9},
  {
    value: 84,
    label: 'بغلان جيد',
    district_pa: 'بغلان جيد',
    districtcode: '0905',
    provincecode: 9,
  },
  {value: 85, label: 'خنجان', district_pa: 'خنجان', districtcode: '0906', provincecode: 9},
  {value: 86, label: 'اندراب', district_pa: 'اندراب', districtcode: '0907', provincecode: 9},
  {value: 87, label: 'ده صلاح', district_pa: 'ده صلاح', districtcode: '0908', provincecode: 9},
  {value: 88, label: 'جلگه', district_pa: 'جلگه', districtcode: '0909', provincecode: 9},
  {value: 89, label: 'برکه', district_pa: 'برکه', districtcode: '0910', provincecode: 9},
  {
    value: 90,
    label: 'تاله وبرفک',
    district_pa: 'تاله وبرفک',
    districtcode: '0911',
    provincecode: 9,
  },
  {value: 91, label: 'پل حصار', district_pa: 'پل حصار', districtcode: '0912', provincecode: 9},
  {
    value: 92,
    label: 'خوست و فرنگ',
    district_pa: 'خوست و فرنگ',
    districtcode: '0913',
    provincecode: 9,
  },
  {
    value: 93,
    label: 'گذرگاه نور',
    district_pa: 'گذرگاه نور',
    districtcode: '0914',
    provincecode: 9,
  },
  {
    value: 94,
    label: 'فرنگ وغارو',
    district_pa: 'فرنگ وغارو',
    districtcode: '0915',
    provincecode: 9,
  },
  {
    value: 95,
    label: 'باميان',
    district_pa: 'باميان',
    districtcode: '1001',
    provincecode: 10,
  },
  {value: 96, label: 'شيبر', district_pa: 'شيبر', districtcode: '1002', provincecode: 10},
  {value: 97, label: 'سيغان', district_pa: 'سيغان', districtcode: '1003', provincecode: 10},
  {value: 98, label: 'کهمرد', district_pa: 'کهمرد', districtcode: '1004', provincecode: 10},
  {value: 99, label: 'يکاولنگ', district_pa: 'يکاولنگ', districtcode: '1005', provincecode: 10},
  {value: 100, label: 'پنجاب', district_pa: 'پنجاب', districtcode: '1006', provincecode: 10},
  {value: 101, label: 'ورس', district_pa: 'ورس', districtcode: '1007', provincecode: 10},
  {
    value: 102,
    label: 'غزني',
    district_pa: 'غزني',
    districtcode: '1101',
    provincecode: 11,
  },
  {
    value: 103,
    label: 'ولي محمد شهيد خوگياني',
    district_pa: 'ولي محمد شهيد خوگياني',
    districtcode: '1102',
    provincecode: 11,
  },
  {
    value: 104,
    label: 'خواجه عمري',
    district_pa: 'خواجه عمري',
    districtcode: '1103',
    provincecode: 11,
  },
  {value: 105, label: 'واغظ', district_pa: 'واغظ', districtcode: '1104', provincecode: 11},
  {value: 106, label: 'ده يک', district_pa: 'ده يک', districtcode: '1105', provincecode: 11},
  {value: 107, label: 'جغتو', district_pa: 'جغتو', districtcode: '1106', provincecode: 11},
  {value: 108, label: 'اندر', district_pa: 'اندر', districtcode: '1107', provincecode: 11},
  {value: 109, label: 'زنخان', district_pa: 'زنخان', districtcode: '1108', provincecode: 11},
  {value: 110, label: 'رشيدان', district_pa: 'رشيدان', districtcode: '1109', provincecode: 11},
  {value: 111, label: 'ناور', district_pa: 'ناور', districtcode: '1110', provincecode: 11},
  {value: 112, label: 'قره باغ', district_pa: 'قره باغ', districtcode: '1111', provincecode: 11},
  {value: 113, label: 'گيرو', district_pa: 'گيرو', districtcode: '1112', provincecode: 11},
  {value: 114, label: 'آب بند', district_pa: 'آب بند', districtcode: '1113', provincecode: 11},
  {value: 115, label: 'جاغوري', district_pa: 'جاغوري', districtcode: '1114', provincecode: 11},
  {value: 116, label: 'مقر', district_pa: 'مقر', districtcode: '1115', provincecode: 11},
  {value: 117, label: 'مالستان', district_pa: 'مالستان', districtcode: '1116', provincecode: 11},
  {value: 118, label: 'گيلان', district_pa: 'گيلان', districtcode: '1117', provincecode: 11},
  {value: 119, label: 'اجرستان', district_pa: 'اجرستان', districtcode: '1118', provincecode: 11},
  {value: 120, label: 'ناوه', district_pa: 'ناوه', districtcode: '1119', provincecode: 11},
  {
    value: 121,
    label: 'شرن',
    district_pa: 'شرن',
    districtcode: '1201',
    provincecode: 12,
  },
  {value: 122, label: 'متاخان', district_pa: 'متاخان', districtcode: '1202', provincecode: 12},
  {
    value: 123,
    label: 'يوسف خيل',
    district_pa: 'يوسف خيل',
    districtcode: '1203',
    provincecode: 12,
  },
  {
    value: 124,
    label: 'يحيي خيل',
    district_pa: 'يحيي خيل',
    districtcode: '1204',
    provincecode: 12,
  },
  {value: 125, label: 'سرروضه', district_pa: 'سرروضه', districtcode: '1205', provincecode: 12},
  {value: 126, label: 'اومنه', district_pa: 'اومنه', districtcode: '1206', provincecode: 12},
  {
    value: 127,
    label: 'زرغون شهر',
    district_pa: 'زرغون شهر',
    districtcode: '1207',
    provincecode: 12,
  },
  {value: 128, label: 'گومل', district_pa: 'گومل', districtcode: '1208', provincecode: 12},
  {
    value: 129,
    label: 'جاني خيل',
    district_pa: 'جاني خيل',
    districtcode: '1209',
    provincecode: 12,
  },
  {
    value: 130,
    label: 'گرديز',
    district_pa: 'گرديز',
    districtcode: '1301',
    provincecode: 13,
  },
  {value: 131, label: 'سروبي', district_pa: 'سروبي', districtcode: '1210', provincecode: 12},
  {value: 132, label: 'اورگون', district_pa: 'اورگون', districtcode: '1211', provincecode: 12},
  {value: 133, label: 'زيروک', district_pa: 'زيروک', districtcode: '1212', provincecode: 12},
  {value: 134, label: 'نيکه', district_pa: 'نيکه', districtcode: '1213', provincecode: 12},
  {value: 135, label: 'برمل', district_pa: 'برمل', districtcode: '1214', provincecode: 12},
  {value: 136, label: 'گيان', district_pa: 'گيان', districtcode: '1215', provincecode: 12},
  {
    value: 137,
    label: 'ديله و خوش آمند',
    district_pa: 'ديله و خوش آمند',
    districtcode: '1216',
    provincecode: 12,
  },
  {
    value: 138,
    label: 'وازه خوا',
    district_pa: 'وازه خوا',
    districtcode: '1217',
    provincecode: 12,
  },
  {value: 139, label: 'ورممي', district_pa: 'ورممي', districtcode: '1218', provincecode: 12},
  {value: 140, label: 'تروو', district_pa: 'تروو', districtcode: '1219', provincecode: 12},
  {value: 141, label: 'احمدآبا', district_pa: 'احمدآبا', districtcode: '1302', provincecode: 13},
  {value: 142, label: 'زرمت', district_pa: 'زرمت', districtcode: '1303', provincecode: 13},
  {value: 143, label: 'شواک', district_pa: 'شواک', districtcode: '1304', provincecode: 13},
  {
    value: 144,
    label: 'وزه ځدران',
    district_pa: 'وزه ځدران',
    districtcode: '1305',
    provincecode: 13,
  },
  {value: 145, label: 'سيدکرم', district_pa: 'سيدکرم', districtcode: '1306', provincecode: 13},
  {value: 146, label: 'جاجي', district_pa: 'جاجي', districtcode: '1307', provincecode: 13},
  {
    value: 147,
    label: 'لجه احمدخيل',
    district_pa: 'لجه احمدخيل',
    districtcode: '1308',
    provincecode: 13,
  },
  {
    value: 148,
    label: 'جاني خيل',
    district_pa: 'جاني خيل',
    districtcode: '1309',
    provincecode: 13,
  },
  {value: 149, label: 'څمکنی', district_pa: 'څمکنی', districtcode: '1310', provincecode: 13},
  {
    value: 150,
    label: 'دند پتان',
    district_pa: 'دند پتان',
    districtcode: '1311',
    provincecode: 13,
  },
  {
    value: 151,
    label: 'خوست',
    district_pa: 'خوست',
    districtcode: '1401',
    provincecode: 14,
  },
  {
    value: 152,
    label: '(مندوزي) اسماعيل خيل',
    district_pa: '(مندوزي) اسماعيل خيل',
    districtcode: '1402',
    provincecode: 14,
  },
  {value: 153, label: 'گربز', district_pa: 'گربز', districtcode: '1403', provincecode: 14},
  {value: 154, label: 'تني', district_pa: 'تني', districtcode: '1404', provincecode: 14},
  {
    value: 155,
    label: 'موسي خيل',
    district_pa: 'موسي خيل',
    districtcode: '1405',
    provincecode: 14,
  },
  {
    value: 156,
    label: 'نادرشاه کوت',
    district_pa: 'نادرشاه کوت',
    districtcode: '1406',
    provincecode: 14,
  },
  {
    value: 157,
    label: '(صبري) يعقوبي',
    district_pa: '(صبري) يعقوبي',
    districtcode: '1407',
    provincecode: 14,
  },
  {value: 158, label: 'علي شير', district_pa: 'علي شير', districtcode: '1408', provincecode: 14},
  {value: 159, label: 'باک', district_pa: 'باک', districtcode: '1409', provincecode: 14},
  {value: 160, label: 'قلندر', district_pa: 'قلندر', districtcode: '1410', provincecode: 14},
  {value: 161, label: 'اسپيره', district_pa: 'اسپيره', districtcode: '1411', provincecode: 14},
  {value: 162, label: 'شمل', district_pa: 'شمل', districtcode: '1412', provincecode: 14},
  {
    value: 163,
    label: 'جاجي ميدان',
    district_pa: 'جاجي ميدان',
    districtcode: '1413',
    provincecode: 14,
  },
  {value: 164, label: 'دانگام', district_pa: 'دانگام', districtcode: '1512', provincecode: 15},
  {
    value: 165,
    label: 'اسدآباد',
    district_pa: 'اسدآباد',
    districtcode: '1501',
    provincecode: 15,
  },
  {value: 166, label: 'مره وره', district_pa: 'مره وره', districtcode: '1502', provincecode: 15},
  {
    value: 167,
    label: 'واته پور',
    district_pa: 'واته پور',
    districtcode: '1503',
    provincecode: 15,
  },
  {
    value: 168,
    label: 'نرنگ وباديل',
    district_pa: 'نرنگ وباديل',
    districtcode: '1504',
    provincecode: 15,
  },
  {value: 169, label: 'سرکاني', district_pa: 'سرکاني', districtcode: '1505', provincecode: 15},
  {
    value: 170,
    label: 'شيگل و شيلتن',
    district_pa: 'شيگل و شيلتن',
    districtcode: '1506',
    provincecode: 15,
  },
  {value: 171, label: 'دره پيچ', district_pa: 'دره پيچ', districtcode: '1507', provincecode: 15},
  {value: 172, label: 'برکنر', district_pa: 'برکنر', districtcode: '1508', provincecode: 15},
  {value: 173, label: 'څوکی', district_pa: 'څوکی', districtcode: '1509', provincecode: 15},
  {value: 174, label: 'خاص کنر', district_pa: 'خاص کنر', districtcode: '1510', provincecode: 15},
  {
    value: 175,
    label: 'غازي آباد',
    district_pa: 'غازي آباد',
    districtcode: '1511',
    provincecode: 15,
  },
  {value: 176, label: 'چپه دره', district_pa: 'چپه دره', districtcode: '1513', provincecode: 15},
  {value: 177, label: 'نورگل', district_pa: 'نورگل', districtcode: '1514', provincecode: 15},
  {value: 178, label: 'نري', district_pa: 'نري', districtcode: '1515', provincecode: 15},
  {
    value: 179,
    label: 'پارون',
    district_pa: 'پارون',
    districtcode: '1601',
    provincecode: 16,
  },
  {value: 180, label: 'وايگل', district_pa: 'وايگل', districtcode: '1602', provincecode: 16},
  {value: 181, label: 'واما', district_pa: 'واما', districtcode: '1603', provincecode: 16},
  {value: 182, label: 'نورگرام', district_pa: 'نورگرام', districtcode: '1604', provincecode: 16},
  {value: 183, label: 'دوآب', district_pa: 'دوآب', districtcode: '1605', provincecode: 16},
  {value: 184, label: 'کامديش', district_pa: 'کامديش', districtcode: '1606', provincecode: 16},
  {value: 185, label: 'مندول', district_pa: 'مندول', districtcode: '1607', provincecode: 16},
  {
    value: 186,
    label: 'برگ متال',
    district_pa: 'برگ متال',
    districtcode: '1608',
    provincecode: 16,
  },
  {
    value: 187,
    label: 'فيض آباد',
    district_pa: 'فيض آباد',
    districtcode: '1701',
    provincecode: 17,
  },
  {value: 188, label: 'ارگو', district_pa: 'ارگو', districtcode: '1702', provincecode: 17},
  {
    value: 189,
    label: 'ارغنجخواه',
    district_pa: 'ارغنجخواه',
    districtcode: '1703',
    provincecode: 17,
  },
  {
    value: 190,
    label: 'يفتل سفلي',
    district_pa: 'يفتل سفلي',
    districtcode: '1704',
    provincecode: 17,
  },
  {value: 191, label: 'خاش', district_pa: 'خاش', districtcode: '1705', provincecode: 17},
  {value: 192, label: 'بهارک', district_pa: 'بهارک', districtcode: '1706', provincecode: 17},
  {value: 193, label: 'درايم', district_pa: 'درايم', districtcode: '1707', provincecode: 17},
  {value: 194, label: 'کوهستان', district_pa: 'کوهستان', districtcode: '1708', provincecode: 17},
  {value: 195, label: 'ياوان', district_pa: 'ياوان', districtcode: '1709', provincecode: 17},
  {value: 196, label: 'جرم', district_pa: 'جرم', districtcode: '1710', provincecode: 17},
  {value: 197, label: 'تشکان', district_pa: 'تشکان', districtcode: '1711', provincecode: 17},
  {value: 198, label: 'شهدا', district_pa: 'شهدا', districtcode: '1712', provincecode: 17},
  {value: 199, label: 'شهربزرگ', district_pa: 'شهربزرگ', districtcode: '1713', provincecode: 17},
  {value: 200, label: 'راغستان', district_pa: 'راغستان', districtcode: '1714', provincecode: 17},
  {value: 201, label: 'کشم', district_pa: 'کشم', districtcode: '1715', provincecode: 17},
  {value: 202, label: 'وردوج', district_pa: 'وردوج', districtcode: '1716', provincecode: 17},
  {value: 203, label: 'تگاب', district_pa: 'تگاب', districtcode: '1717', provincecode: 17},
  {value: 204, label: 'يمگان', district_pa: 'يمگان', districtcode: '1718', provincecode: 17},
  {value: 205, label: 'شغنان', district_pa: 'شغنان', districtcode: '1719', provincecode: 17},
  {value: 206, label: 'خواهان', district_pa: 'خواهان', districtcode: '1720', provincecode: 17},
  {value: 207, label: 'کوف آب', district_pa: 'کوف آب', districtcode: '1721', provincecode: 17},
  {
    value: 208,
    label: 'درواز پائين مايمي',
    district_pa: 'درواز پائين مايمي',
    districtcode: '1722',
    provincecode: 17,
  },
  {value: 209, label: 'اشکاشم', district_pa: 'اشکاشم', districtcode: '1723', provincecode: 17},
  {value: 210, label: 'شکي', district_pa: 'شکي', districtcode: '1724', provincecode: 17},
  {value: 211, label: 'زيباک', district_pa: 'زيباک', districtcode: '1725', provincecode: 17},
  {
    value: 212,
    label: 'کران ومنجان',
    district_pa: 'کران ومنجان',
    districtcode: '1726',
    provincecode: 17,
  },
  {
    value: 213,
    label: 'درواز بالا نسي',
    district_pa: 'درواز بالا نسي',
    districtcode: '1727',
    provincecode: 17,
  },
  {value: 214, label: 'واخان', district_pa: 'واخان', districtcode: '1728', provincecode: 17},
  {
    value: 215,
    label: 'تالقان',
    district_pa: 'تالقان',
    districtcode: '1801',
    provincecode: 18,
  },
  {
    value: 216,
    label: 'هزارسموچ',
    district_pa: 'هزارسموچ',
    districtcode: '1802',
    provincecode: 18,
  },
  {value: 217, label: 'بهارک', district_pa: 'بهارک', districtcode: '1803', provincecode: 18},
  {value: 218, label: 'بنگي', district_pa: 'بنگي', districtcode: '1804', provincecode: 18},
  {value: 219, label: 'چال', district_pa: 'چال', districtcode: '1805', provincecode: 18},
  {value: 220, label: 'نمک آب', district_pa: 'نمک آب', districtcode: '1806', provincecode: 18},
  {value: 221, label: 'کلفگان', district_pa: 'کلفگان', districtcode: '1807', provincecode: 18},
  {value: 222, label: 'فرخار', district_pa: 'فرخار', districtcode: '1808', provincecode: 18},
  {
    value: 223,
    label: 'خواجه غار',
    district_pa: 'خواجه غار',
    districtcode: '1809',
    provincecode: 18,
  },
  {value: 224, label: 'رستاق', district_pa: 'رستاق', districtcode: '1810', provincecode: 18},
  {value: 225, label: 'اشکمش', district_pa: 'اشکمش', districtcode: '1811', provincecode: 18},
  {
    value: 226,
    label: 'دشت قلعه',
    district_pa: 'دشت قلعه',
    districtcode: '1812',
    provincecode: 18,
  },
  {value: 227, label: 'ورسج', district_pa: 'ورسج', districtcode: '1813', provincecode: 18},
  {
    value: 228,
    label: 'خواجه بهاوالدين',
    district_pa: 'خواجه بهاوالدين',
    districtcode: '1814',
    provincecode: 18,
  },
  {value: 229, label: 'درقد', district_pa: 'درقد', districtcode: '1815', provincecode: 18},
  {value: 230, label: 'چاه آب', district_pa: 'چاه آب', districtcode: '1816', provincecode: 18},
  {
    value: 231,
    label: 'ينگي قلعه',
    district_pa: 'ينگي قلعه',
    districtcode: '1817',
    provincecode: 18,
  },
  {
    value: 232,
    label: 'کندز',
    district_pa: 'کندز',
    districtcode: '1901',
    provincecode: 19,
  },
  {value: 233, label: 'چاردره', district_pa: 'چاردره', districtcode: '1902', provincecode: 19},
  {
    value: 234,
    label: 'علي آباد',
    district_pa: 'علي آباد',
    districtcode: '1903',
    provincecode: 19,
  },
  {
    value: 235,
    label: 'خان آباد',
    district_pa: 'خان آباد',
    districtcode: '1904',
    provincecode: 19,
  },
  {
    value: 236,
    label: 'حضرت امام صاحب',
    district_pa: 'حضرت امام صاحب',
    districtcode: '1905',
    provincecode: 19,
  },
  {
    value: 237,
    label: 'دشت ارچي',
    district_pa: 'دشت ارچي',
    districtcode: '1906',
    provincecode: 19,
  },
  {
    value: 238,
    label: 'قلعه ذال',
    district_pa: 'قلعه ذال',
    districtcode: '1907',
    provincecode: 19,
  },
  {
    value: 239,
    label: 'ايبک',
    district_pa: 'ايبک',
    districtcode: '2001',
    provincecode: 20,
  },
  {
    value: 240,
    label: 'حضرت سلطان',
    district_pa: 'حضرت سلطان',
    districtcode: '2002',
    provincecode: 20,
  },
  {
    value: 241,
    label: 'خرم و سارباغ',
    district_pa: 'خرم و سارباغ',
    districtcode: '2003',
    provincecode: 20,
  },
  {
    value: 242,
    label: 'فيروزنخچير',
    district_pa: 'فيروزنخچير',
    districtcode: '2004',
    provincecode: 20,
  },
  {
    value: 243,
    label: 'روي دوآب',
    district_pa: 'روي دوآب',
    districtcode: '2005',
    provincecode: 20,
  },
  {
    value: 244,
    label: 'دره صوف پائين',
    district_pa: 'دره صوف پائين',
    districtcode: '2006',
    provincecode: 20,
  },
  {
    value: 245,
    label: 'دره صوف  بالا',
    district_pa: 'دره صوف  بالا',
    districtcode: '2007',
    provincecode: 20,
  },
  {
    value: 246,
    label: 'نهر شاهي',
    district_pa: 'نهر شاهي',
    districtcode: '2102',
    provincecode: 21,
  },
  {value: 247, label: 'دهدادي', district_pa: 'دهدادي', districtcode: '2103', provincecode: 21},
  {value: 248, label: 'چارکنت', district_pa: 'چارکنت', districtcode: '2104', provincecode: 21},
  {value: 249, label: 'مارمل', district_pa: 'مارمل', districtcode: '2105', provincecode: 21},
  {value: 250, label: 'بلخ', district_pa: 'بلخ', districtcode: '2106', provincecode: 21},
  {value: 251, label: 'شولگره', district_pa: 'شولگره', districtcode: '2107', provincecode: 21},
  {value: 252, label: 'چمتال', district_pa: 'چمتال', districtcode: '2108', provincecode: 21},
  {
    value: 253,
    label: 'دولت آباد',
    district_pa: 'دولت آباد',
    districtcode: '2109',
    provincecode: 21,
  },
  {value: 254, label: 'خلم', district_pa: 'خلم', districtcode: '2110', provincecode: 21},
  {value: 255, label: 'چاربولک', district_pa: 'چاربولک', districtcode: '2111', provincecode: 21},
  {value: 256, label: 'شورتيپه', district_pa: 'شورتيپه', districtcode: '2112', provincecode: 21},
  {value: 257, label: 'کلدار', district_pa: 'کلدار', districtcode: '2113', provincecode: 21},
  {value: 258, label: 'کشنده', district_pa: 'کشنده', districtcode: '2114', provincecode: 21},
  {value: 259, label: 'زاري', district_pa: 'زاري', districtcode: '2115', provincecode: 21},
  {
    value: 260,
    label: 'سرپل',
    district_pa: 'سرپل',
    districtcode: '2201',
    provincecode: 22,
  },
  {value: 261, label: 'صياد', district_pa: 'صياد', districtcode: '2202', provincecode: 22},
  {
    value: 262,
    label: 'کوهستانات',
    district_pa: 'کوهستانات',
    districtcode: '2203',
    provincecode: 22,
  },
  {
    value: 263,
    label: 'سوزمه قلعه',
    district_pa: 'سوزمه قلعه',
    districtcode: '2204',
    provincecode: 22,
  },
  {
    value: 264,
    label: 'سنگ چارک',
    district_pa: 'سنگ چارک',
    districtcode: '2205',
    provincecode: 22,
  },
  {value: 265, label: 'گوسفندي', district_pa: 'گوسفندي', districtcode: '2206', provincecode: 22},
  {value: 266, label: 'بلخاب', district_pa: 'بلخاب', districtcode: '2207', provincecode: 22},
  {
    value: 267,
    label: 'چغچران',
    district_pa: 'چغچران',
    districtcode: '2301',
    provincecode: 23,
  },
  {value: 268, label: 'دولينه', district_pa: 'دولينه', districtcode: '2302', provincecode: 23},
  {
    value: 269,
    label: 'دولت يار',
    district_pa: 'دولت يار',
    districtcode: '2303',
    provincecode: 23,
  },
  {value: 270, label: 'چارصده', district_pa: 'چارصده', districtcode: '2304', provincecode: 23},
  {value: 271, label: 'پسابند', district_pa: 'پسابند', districtcode: '2305', provincecode: 23},
  {value: 272, label: 'شهرک', district_pa: 'شهرک', districtcode: '2306', provincecode: 23},
  {
    value: 273,
    label: 'لعل وسرجنگل',
    district_pa: 'لعل وسرجنگل',
    districtcode: '2307',
    provincecode: 23,
  },
  {value: 274, label: 'تيوره', district_pa: 'تيوره', districtcode: '2308', provincecode: 23},
  {value: 275, label: 'تولک', district_pa: 'تولک', districtcode: '2309', provincecode: 23},
  {value: 276, label: 'ساغر', district_pa: 'ساغر', districtcode: '2310', provincecode: 23},
  {
    value: 277,
    label: 'نيلي',
    district_pa: 'نيلي',
    districtcode: '2401',
    provincecode: 24,
  },
  {value: 278, label: 'شهرستان', district_pa: 'شهرستان', districtcode: '2402', provincecode: 24},
  {value: 279, label: 'گيزاب', district_pa: 'گيزاب', districtcode: '2403', provincecode: 24},
  {value: 280, label: 'اشترلي', district_pa: 'اشترلي', districtcode: '2404', provincecode: 24},
  {value: 281, label: 'خدير', district_pa: 'خدير', districtcode: '2405', provincecode: 24},
  {value: 282, label: 'گيتي', district_pa: 'گيتي', districtcode: '2406', provincecode: 24},
  {value: 283, label: 'ميرامور', district_pa: 'ميرامور', districtcode: '2407', provincecode: 24},
  {value: 284, label: 'سنگ تخت', district_pa: 'سنگ تخت', districtcode: '2408', provincecode: 24},
  {value: 285, label: 'کيجران', district_pa: 'کيجران', districtcode: '2409', provincecode: 24},
  {
    value: 286,
    label: 'ترينکوت',
    district_pa: 'ترينکوت',
    districtcode: '2501',
    provincecode: 25,
  },
  {value: 287, label: 'دهراود', district_pa: 'دهراود', districtcode: '2502', provincecode: 25},
  {value: 288, label: 'چوره', district_pa: 'چوره', districtcode: '2503', provincecode: 25},
  {
    value: 289,
    label: 'شهيد حساس',
    district_pa: 'شهيد حساس',
    districtcode: '2504',
    provincecode: 25,
  },
  {
    value: 290,
    label: 'خاص ارزگان',
    district_pa: 'خاص ارزگان',
    districtcode: '2505',
    provincecode: 25,
  },
  {
    value: 291,
    label: 'قلات',
    district_pa: 'قلات',
    districtcode: '2601',
    provincecode: 26,
  },
  {
    value: 292,
    label: 'ترنک وجلدک',
    district_pa: 'ترنک وجلدک',
    districtcode: '2602',
    provincecode: 26,
  },
  {value: 293, label: 'شينکي', district_pa: 'شينکي', districtcode: '2603', provincecode: 26},
  {value: 294, label: 'ميزان', district_pa: 'ميزان', districtcode: '2604', provincecode: 26},
  {value: 295, label: 'ارغنداب', district_pa: 'ارغنداب', districtcode: '2605', provincecode: 26},
  {value: 296, label: 'شاه جوي', district_pa: 'شاه جوي', districtcode: '2606', provincecode: 26},
  {
    value: 297,
    label: 'دايچوپان',
    district_pa: 'دايچوپان',
    districtcode: '2607',
    provincecode: 26,
  },
  {value: 298, label: 'اتغر', district_pa: 'اتغر', districtcode: '2608', provincecode: 26},
  {value: 299, label: 'نوبهار', district_pa: 'نوبهار', districtcode: '2609', provincecode: 26},
  {value: 300, label: 'شملزايي', district_pa: 'شملزايي', districtcode: '2610', provincecode: 26},
  {
    value: 301,
    label: '(کاکري) خاک افغان',
    district_pa: '(کاکري) خاک افغان',
    districtcode: '2611',
    provincecode: 26,
  },
  {
    value: 302,
    label: 'کندهار',
    district_pa: 'کندهار',
    districtcode: '2701',
    provincecode: 27,
  },
  {value: 303, label: 'ارغنداب', district_pa: 'ارغنداب', districtcode: '2702', provincecode: 27},
  {value: 304, label: 'دامان', district_pa: 'دامان', districtcode: '2703', provincecode: 27},
  {value: 305, label: 'پنجوائي', district_pa: 'پنجوائي', districtcode: '2704', provincecode: 27},
  {value: 306, label: 'ژيري', district_pa: 'ژيري', districtcode: '2705', provincecode: 27},
  {
    value: 307,
    label: 'شاه ولي کوت',
    district_pa: 'شاه ولي کوت',
    districtcode: '2706',
    provincecode: 27,
  },
  {value: 308, label: 'خاکريز', district_pa: 'خاکريز', districtcode: '2707', provincecode: 27},
  {value: 309, label: 'ارغستان', district_pa: 'ارغستان', districtcode: '2708', provincecode: 27},
  {value: 310, label: 'آقچه', district_pa: 'آقچه', districtcode: '2807', provincecode: 28},
  {value: 311, label: 'غورک', district_pa: 'غورک', districtcode: '2709', provincecode: 27},
  {value: 312, label: 'ميوند', district_pa: 'ميوند', districtcode: '2710', provincecode: 27},
  {
    value: 313,
    label: 'سپين بولدک',
    district_pa: 'سپين بولدک',
    districtcode: '2711',
    provincecode: 27,
  },
  {value: 314, label: 'نيش', district_pa: 'نيش', districtcode: '2712', provincecode: 27},
  {value: 315, label: 'ميانشين', district_pa: 'ميانشين', districtcode: '2713', provincecode: 27},
  {value: 316, label: 'شورابک', district_pa: 'شورابک', districtcode: '2714', provincecode: 27},
  {value: 317, label: 'معروف', district_pa: 'معروف', districtcode: '2715', provincecode: 27},
  {
    value: 318,
    label: 'ريگ(شگه)',
    district_pa: 'ريگ(شگه)',
    districtcode: '2716',
    provincecode: 27,
  },
  {
    value: 319,
    label: 'شبرغان',
    district_pa: 'شبرغان',
    districtcode: '2801',
    provincecode: 28,
  },
  {value: 320, label: 'کوهستان', district_pa: 'کوهستان', districtcode: '2910', provincecode: 29},
  {
    value: 321,
    label: 'خواجه دوکوه',
    district_pa: 'خواجه دوکوه',
    districtcode: '2802',
    provincecode: 28,
  },
  {value: 322, label: 'خانقاً', district_pa: 'خانقاً', districtcode: '2803', provincecode: 28},
  {value: 323, label: 'منگجيک', district_pa: 'منگجيک', districtcode: '2804', provincecode: 28},
  {
    value: 324,
    label: 'قوش تيپه',
    district_pa: 'قوش تيپه',
    districtcode: '2805',
    provincecode: 28,
  },
  {value: 325, label: 'خم آب', district_pa: 'خم آب', districtcode: '2806', provincecode: 28},
  {
    value: 326,
    label: 'فيض آباد',
    district_pa: 'فيض آباد',
    districtcode: '2808',
    provincecode: 28,
  },
  {value: 327, label: 'مرديان', district_pa: 'مرديان', districtcode: '2809', provincecode: 28},
  {value: 328, label: 'قرقين', district_pa: 'قرقين', districtcode: '2810', provincecode: 28},
  {value: 329, label: 'درز آب', district_pa: 'درز آب', districtcode: '2811', provincecode: 28},
  {
    value: 330,
    label: 'پشتون کوت',
    district_pa: 'پشتون کوت',
    districtcode: '2902',
    provincecode: 29,
  },
  {
    value: 331,
    label: 'خواجه سبز پوش ولي',
    district_pa: 'خواجه سبز پوش ولي',
    districtcode: '2903',
    provincecode: 29,
  },
  {value: 332, label: 'المار', district_pa: 'المار', districtcode: '2904', provincecode: 29},
  {value: 333, label: 'بل چراغ', district_pa: 'بل چراغ', districtcode: '2905', provincecode: 29},
  {
    value: 334,
    label: 'شرين تگاب',
    district_pa: 'شرين تگاب',
    districtcode: '2906',
    provincecode: 29,
  },
  {value: 335, label: 'قيصار', district_pa: 'قيصار', districtcode: '2907', provincecode: 29},
  {value: 336, label: 'گرزيوان', district_pa: 'گرزيوان', districtcode: '2908', provincecode: 29},
  {
    value: 337,
    label: 'دولت آباد',
    district_pa: 'دولت آباد',
    districtcode: '2909',
    provincecode: 29,
  },
  {value: 338, label: 'قرمقول', district_pa: 'قرمقول', districtcode: '2911', provincecode: 29},
  {value: 339, label: 'قرغان', district_pa: 'قرغان', districtcode: '2912', provincecode: 29},
  {value: 340, label: 'اندخوي', district_pa: 'اندخوي', districtcode: '2913', provincecode: 29},
  {
    value: 341,
    label: 'خان چارباغ',
    district_pa: 'خان چارباغ',
    districtcode: '2914',
    provincecode: 29,
  },
  {
    value: 342,
    label: 'لشکرگاه',
    district_pa: 'لشکرگاه',
    districtcode: '3001',
    provincecode: 30,
  },
  {value: 343, label: 'نادعلي', district_pa: 'نادعلي', districtcode: '3002', provincecode: 30},
  {
    value: 344,
    label: 'نـاوه بـارکـزائـي',
    district_pa: 'نـاوه بـارکـزائـي',
    districtcode: '3003',
    provincecode: 30,
  },
  {
    value: 345,
    label: 'نـهـر ســراج',
    district_pa: 'نـهـر ســراج',
    districtcode: '3004',
    provincecode: 30,
  },
  {
    value: 346,
    label: 'واشـــيــر',
    district_pa: 'واشـــيــر',
    districtcode: '3005',
    provincecode: 30,
  },
  {value: 347, label: 'گرم سير', district_pa: 'گرم سير', districtcode: '3006', provincecode: 30},
  {value: 348, label: 'نوزاد', district_pa: 'نوزاد', districtcode: '3007', provincecode: 30},
  {
    value: 349,
    label: 'سنگـيــن قـلــعه',
    district_pa: 'سنگـيــن قـلــعه',
    districtcode: '3008',
    provincecode: 30,
  },
  {
    value: 350,
    label: 'مــوســي قـلــعـه',
    district_pa: 'مــوســي قـلــعـه',
    districtcode: '3009',
    provincecode: 30,
  },
  {value: 351, label: 'کجکي', district_pa: 'کجکي', districtcode: '3010', provincecode: 30},
  {
    value: 352,
    label: 'ريـک خـانـشــيـن',
    district_pa: 'ريـک خـانـشــيـن',
    districtcode: '3011',
    provincecode: 30,
  },
  {value: 353, label: 'باغران', district_pa: 'باغران', districtcode: '3012', provincecode: 30},
  {value: 354, label: 'ديشو', district_pa: 'ديشو', districtcode: '3013', provincecode: 30},
  {
    value: 355,
    label: 'قلعه نو',
    district_pa: 'قلعه نو',
    districtcode: '3101',
    provincecode: 31,
  },
  {
    value: 356,
    label: 'آبکمــري',
    district_pa: 'آبکمــري',
    districtcode: '3102',
    provincecode: 31,
  },
  {value: 357, label: 'کرخ', district_pa: 'کرخ', districtcode: '3204', provincecode: 32},
  {value: 358, label: 'مقـــر', district_pa: 'مقـــر', districtcode: '3103', provincecode: 31},
  {value: 359, label: 'قادس', district_pa: 'قادس', districtcode: '3104', provincecode: 31},
  {
    value: 360,
    label: 'بالامــرغــاب',
    district_pa: 'بالامــرغــاب',
    districtcode: '3105',
    provincecode: 31,
  },
  {value: 361, label: 'جونـد', district_pa: 'جونـد', districtcode: '3106', provincecode: 31},
  {
    value: 362,
    label: 'غـورمــاچ',
    district_pa: 'غـورمــاچ',
    districtcode: '3107',
    provincecode: 31,
  },
  {value: 363, label: 'انجيل', district_pa: 'انجيل', districtcode: '3202', provincecode: 32},
  {
    value: 364,
    label: '(نظام شهيد) گذره',
    district_pa: '(نظام شهيد) گذره',
    districtcode: '3203',
    provincecode: 32,
  },
  {
    value: 365,
    label: 'زنده جان',
    district_pa: 'زنده جان',
    districtcode: '3205',
    provincecode: 32,
  },
  {
    value: 366,
    label: 'پشتون زرغون',
    district_pa: 'پشتون زرغون',
    districtcode: '3206',
    provincecode: 32,
  },
  {
    value: 367,
    label: '(کشک) رباط سنگي',
    district_pa: '(کشک) رباط سنگي',
    districtcode: '3207',
    provincecode: 32,
  },
  {value: 368, label: 'گلران', district_pa: 'گلران', districtcode: '3208', provincecode: 32},
  {value: 369, label: 'ادرسکن', district_pa: 'ادرسکن', districtcode: '3209', provincecode: 32},
  {
    value: 370,
    label: 'کشک کهنه',
    district_pa: 'کشک کهنه',
    districtcode: '3210',
    provincecode: 32,
  },
  {value: 371, label: 'غوريان', district_pa: 'غوريان', districtcode: '3211', provincecode: 32},
  {value: 372, label: 'اوبه', district_pa: 'اوبه', districtcode: '3212', provincecode: 32},
  {value: 373, label: 'گلستان', district_pa: 'گلستان', districtcode: '3310', provincecode: 33},
  {value: 374, label: 'کهسان', district_pa: 'کهسان', districtcode: '3213', provincecode: 32},
  {value: 375, label: 'شيندند', district_pa: 'شيندند', districtcode: '3214', provincecode: 32},
  {value: 376, label: 'فرسي', district_pa: 'فرسي', districtcode: '3215', provincecode: 32},
  {
    value: 377,
    label: 'چشت شريف',
    district_pa: 'چشت شريف',
    districtcode: '3216',
    provincecode: 32,
  },
  {
    value: 378,
    label: 'فراه',
    district_pa: 'فراه',
    districtcode: '3301',
    provincecode: 33,
  },
  {value: 379, label: 'پشت رود', district_pa: 'پشت رود', districtcode: '3302', provincecode: 33},
  {
    value: 380,
    label: 'خاک سفيد',
    district_pa: 'خاک سفيد',
    districtcode: '3303',
    provincecode: 33,
  },
  {
    value: 381,
    label: 'قلعه کاه',
    district_pa: 'قلعه کاه',
    districtcode: '3304',
    provincecode: 33,
  },
  {value: 382, label: 'شيب کوه', district_pa: 'شيب کوه', districtcode: '3305', provincecode: 33},
  {
    value: 383,
    label: 'بالا بلوک',
    district_pa: 'بالا بلوک',
    districtcode: '3306',
    provincecode: 33,
  },
  {value: 384, label: 'اناردره', district_pa: 'اناردره', districtcode: '3307', provincecode: 33},
  {value: 385, label: 'ناحيه 5', district_pa: 'ناحيه 5', districtcode: '0120', provincecode: 1},
  {value: 386, label: 'بکواه', district_pa: 'بکواه', districtcode: '3308', provincecode: 33},
  {
    value: 387,
    label: 'لاش جوين',
    district_pa: 'لاش جوين',
    districtcode: '3309',
    provincecode: 33,
  },
  {
    value: 388,
    label: 'چهارچينو',
    district_pa: 'چهارچينو',
    districtcode: '2511',
    provincecode: 25,
  },
  {
    value: 389,
    label: 'مزار شريف',
    district_pa: 'مزار شريف',
    districtcode: '2127',
    provincecode: 21,
  },
  {value: 390, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '1609', provincecode: 16},
  {
    value: 392,
    label: 'هرات',
    district_pa: 'هرات',
    districtcode: '3231',
    provincecode: 32,
  },
  {value: 393, label: 'دند', district_pa: 'دند', districtcode: '2735', provincecode: 27},
  {value: 394, label: 'پغمان', district_pa: 'پغمان', districtcode: '0139', provincecode: 1},
  {value: 395, label: 'پرچمن', district_pa: 'پرچمن', districtcode: '3311', provincecode: 33},
  {value: 396, label: 'دلارام', district_pa: '', districtcode: '3408', provincecode: 34},
  {
    value: 397,
    label: 'اسپين غر',
    district_pa: 'اسپين غر',
    districtcode: '0630',
    provincecode: 6,
  },
  {value: 398, label: 'غورماچ', district_pa: 'غورماچ', districtcode: '2927', provincecode: 29},
  {
    value: 399,
    label: 'زرنج',
    district_pa: 'زرنج',
    districtcode: '3401',
    provincecode: 34,
  },
  {value: 400, label: 'کنگ', district_pa: 'کنگ', districtcode: '3402', provincecode: 34},
  {
    value: 401,
    label: 'اصل چخانسور',
    district_pa: 'اصل چخانسور',
    districtcode: '3403',
    provincecode: 34,
  },
  {
    value: 402,
    label: 'چهاربرجک',
    district_pa: 'چهاربرجک',
    districtcode: '3404',
    provincecode: 34,
  },
  {value: 403, label: 'خاشرود', district_pa: 'خاشرود', districtcode: '3405', provincecode: 34},
  {value: 404, label: 'ناحيه1', district_pa: 'ناحيه1', districtcode: '0116', provincecode: 1},
  {value: 405, label: 'ناحيه2', district_pa: 'ناحيه2', districtcode: '0117', provincecode: 1},
  {value: 406, label: 'ناحيه3', district_pa: 'ناحيه3', districtcode: '0118', provincecode: 1},
  {value: 407, label: 'ناحيه 4', district_pa: 'ناحيه 4', districtcode: '0119', provincecode: 1},
  {value: 408, label: 'ناحيه 3', district_pa: 'ناحيه 3', districtcode: '2008', provincecode: 20},
  {
    value: 409,
    label: 'ايلقچي پاين',
    district_pa: 'ايلقچي پاين',
    districtcode: '2116',
    provincecode: 21,
  },
  {value: 410, label: 'ناحيه 6', district_pa: 'ناحيه 6', districtcode: '0121', provincecode: 1},
  {value: 411, label: 'ناحيه 7', district_pa: 'ناحيه 7', districtcode: '0122', provincecode: 1},
  {value: 412, label: 'ناحيه 8', district_pa: 'ناحيه 8', districtcode: '0123', provincecode: 1},
  {value: 413, label: 'ناحيه 9', district_pa: 'ناحيه 9', districtcode: '0124', provincecode: 1},
  {
    value: 414,
    label: 'ناحيه 10',
    district_pa: 'ناحيه 10',
    districtcode: '0125',
    provincecode: 1,
  },
  {
    value: 415,
    label: 'ناحيه 11',
    district_pa: 'ناحيه 11',
    districtcode: '0126',
    provincecode: 1,
  },
  {
    value: 416,
    label: 'ناحيه 12',
    district_pa: 'ناحيه 12',
    districtcode: '0127',
    provincecode: 1,
  },
  {
    value: 417,
    label: 'ناحيه 13',
    district_pa: 'ناحيه 13',
    districtcode: '0128',
    provincecode: 1,
  },
  {
    value: 418,
    label: 'ناحيه 14',
    district_pa: 'ناحيه 14',
    districtcode: '0129',
    provincecode: 1,
  },
  {
    value: 419,
    label: 'ناحيه 15',
    district_pa: 'ناحيه 15',
    districtcode: '0130',
    provincecode: 1,
  },
  {
    value: 420,
    label: 'ناحيه 16',
    district_pa: 'ناحيه 16',
    districtcode: '0131',
    provincecode: 1,
  },
  {
    value: 421,
    label: 'ناحيه 17',
    district_pa: 'ناحيه 17',
    districtcode: '0132',
    provincecode: 1,
  },
  {
    value: 422,
    label: 'ناحيه 18',
    district_pa: 'ناحيه 18',
    districtcode: '0133',
    provincecode: 1,
  },
  {
    value: 423,
    label: 'ناحيه 19',
    district_pa: 'ناحيه 19',
    districtcode: '0134',
    provincecode: 1,
  },
  {
    value: 424,
    label: 'ناحيه 20',
    district_pa: 'ناحيه 20',
    districtcode: '0135',
    provincecode: 1,
  },
  {
    value: 425,
    label: 'ناحيه 21',
    district_pa: 'ناحيه 21',
    districtcode: '0136',
    provincecode: 1,
  },
  {
    value: 426,
    label: 'ناحيه 22',
    district_pa: 'ناحيه 22',
    districtcode: '0137',
    provincecode: 1,
  },
  {value: 427, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '0138', provincecode: 1},
  {value: 428, label: 'ناحيه 1', district_pa: 'ناحيه 1', districtcode: '1729', provincecode: 17},
  {value: 429, label: 'ناحيه 2', district_pa: 'ناحيه 2', districtcode: '1730', provincecode: 17},
  {value: 430, label: 'ناحيه 3', district_pa: 'ناحيه 3', districtcode: '1731', provincecode: 17},
  {value: 431, label: 'ناحيه 4', district_pa: 'ناحيه 4', districtcode: '1732', provincecode: 17},
  {value: 432, label: 'ناحيه 5', district_pa: 'ناحيه 5', districtcode: '1733', provincecode: 17},
  {value: 433, label: 'ناحيه 6', district_pa: 'ناحيه 6', districtcode: '1734', provincecode: 17},
  {value: 434, label: 'ناحيه 7', district_pa: 'ناحيه 7', districtcode: '1735', provincecode: 17},
  {value: 435, label: 'ناحيه 8', district_pa: 'ناحيه 8', districtcode: '1736', provincecode: 17},
  {value: 436, label: 'ناحيه 9', district_pa: 'ناحيه 9', districtcode: '1737', provincecode: 17},
  {
    value: 437,
    label: 'ناحيه 10',
    district_pa: 'ناحيه 10',
    districtcode: '1738',
    provincecode: 17,
  },
  {
    value: 438,
    label: 'ناحيه 11',
    district_pa: 'ناحيه 11',
    districtcode: '1739',
    provincecode: 17,
  },
  {value: 439, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '1740', provincecode: 17},
  {value: 440, label: 'ناحيه 1', district_pa: 'ناحيه 1', districtcode: '2506', provincecode: 25},
  {value: 441, label: 'ناحيه 2', district_pa: 'ناحيه 2', districtcode: '2507', provincecode: 25},
  {value: 442, label: 'ناحيه 3', district_pa: 'ناحيه 3', districtcode: '2508', provincecode: 25},
  {value: 443, label: 'ناحيه 4', district_pa: 'ناحيه 4', districtcode: '2509', provincecode: 25},
  {value: 444, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '2510', provincecode: 25},
  {value: 445, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '3108', provincecode: 31},
  {value: 446, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '1008', provincecode: 10},
  {value: 447, label: 'ناحيه 1', district_pa: 'ناحيه 1', districtcode: '0916', provincecode: 9},
  {value: 448, label: 'ناحيه 2', district_pa: 'ناحيه 2', districtcode: '0917', provincecode: 9},
  {value: 449, label: 'ناحيه 3', district_pa: 'ناحيه 3', districtcode: '0918', provincecode: 9},
  {value: 450, label: 'ناحيه 4', district_pa: 'ناحيه 4', districtcode: '0919', provincecode: 9},
  {value: 451, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '0920', provincecode: 9},
  {value: 452, label: 'ناحيه 1', district_pa: 'ناحيه 1', districtcode: '2117', provincecode: 21},
  {value: 453, label: 'ناحيه 2', district_pa: 'ناحيه 2', districtcode: '2118', provincecode: 21},
  {value: 454, label: 'ناحيه 3', district_pa: 'ناحيه 3', districtcode: '2119', provincecode: 21},
  {value: 455, label: 'ناحيه 4', district_pa: 'ناحيه 4', districtcode: '2120', provincecode: 21},
  {value: 456, label: 'ناحيه 5', district_pa: 'ناحيه 5', districtcode: '2121', provincecode: 21},
  {value: 457, label: 'ناحيه 6', district_pa: 'ناحيه 6', districtcode: '2122', provincecode: 21},
  {value: 458, label: 'ناحيه 7', district_pa: 'ناحيه 7', districtcode: '2123', provincecode: 21},
  {value: 459, label: 'ناحيه 8', district_pa: 'ناحيه 8', districtcode: '2124', provincecode: 21},
  {value: 460, label: 'ناحيه 9', district_pa: 'ناحيه 9', districtcode: '2125', provincecode: 21},
  {value: 461, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '2126', provincecode: 21},
  {value: 462, label: 'ناحيه 1', district_pa: 'ناحيه 1', districtcode: '1818', provincecode: 18},
  {value: 463, label: 'ناحيه 2', district_pa: 'ناحيه 2', districtcode: '1819', provincecode: 18},
  {value: 464, label: 'ناحيه 3', district_pa: 'ناحيه 3', districtcode: '1820', provincecode: 18},
  {value: 465, label: 'ناحيه 4', district_pa: 'ناحيه 4', districtcode: '1821', provincecode: 18},
  {value: 466, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '1822', provincecode: 18},
  {value: 467, label: 'کل باد', district_pa: 'کل باد', districtcode: '1823', provincecode: 18},
  {value: 468, label: 'ناحيه 1', district_pa: 'ناحيه 1', districtcode: '2812', provincecode: 28},
  {value: 469, label: 'ناحيه 2', district_pa: 'ناحيه 2', districtcode: '2813', provincecode: 28},
  {value: 470, label: 'ناحيه 3', district_pa: 'ناحيه 3', districtcode: '2814', provincecode: 28},
  {value: 471, label: 'ناحيه 4', district_pa: 'ناحيه 4', districtcode: '2815', provincecode: 28},
  {value: 472, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '2816', provincecode: 28},
  {value: 473, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '3501', provincecode: 35},
  {value: 474, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '3502', provincecode: 35},
  {value: 475, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '2410', provincecode: 24},
  {value: 476, label: 'ناحيه 1', district_pa: 'ناحيه 1', districtcode: '2411', provincecode: 24},
  {value: 477, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '3312', provincecode: 33},
  {value: 478, label: 'ناحيه 1', district_pa: 'ناحيه 1', districtcode: '3313', provincecode: 33},
  {value: 479, label: 'ناحيه 2', district_pa: 'ناحيه 2', districtcode: '3314', provincecode: 33},
  {value: 480, label: 'ناحيه 3', district_pa: 'ناحيه 3', districtcode: '3315', provincecode: 33},
  {value: 481, label: 'ناحيه 4', district_pa: 'ناحيه 4', districtcode: '3316', provincecode: 33},
  {
    value: 482,
    label: 'نامعلوم',
    district_pa: 'نا معلوم',
    districtcode: '2915',
    provincecode: 29,
  },
  {value: 483, label: 'ناحيه 1', district_pa: 'ناحيه 1', districtcode: '2916', provincecode: 29},
  {value: 484, label: 'ناحيه 2', district_pa: 'ناحيه 2', districtcode: '2917', provincecode: 29},
  {value: 485, label: 'ناحيه 3', district_pa: 'ناحيه 3', districtcode: '2918', provincecode: 29},
  {value: 486, label: 'ناحيه 4', district_pa: 'ناحيه 4', districtcode: '2919', provincecode: 29},
  {value: 487, label: 'ناحيه 5', district_pa: 'ناحيه 5', districtcode: '2920', provincecode: 29},
  {value: 488, label: 'ناحيه 6', district_pa: 'ناحيه 6', districtcode: '2921', provincecode: 29},
  {value: 489, label: 'ناحيه 7', district_pa: 'ناحيه 7', districtcode: '2922', provincecode: 29},
  {value: 490, label: 'ناحيه 8', district_pa: 'ناحيه 8', districtcode: '2923', provincecode: 29},
  {value: 491, label: 'ناحيه 9', district_pa: 'ناحيه 9', districtcode: '2924', provincecode: 29},
  {
    value: 492,
    label: 'ناحيه 10',
    district_pa: 'ناحيه 10',
    districtcode: '2925',
    provincecode: 29,
  },
  {
    value: 493,
    label: '(مرکزولايت فارياب) ميمنه',
    district_pa: '(مرکزولايت فارياب) ميمنه',
    districtcode: '2926',
    provincecode: 29,
  },
  {value: 494, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '1120', provincecode: 11},
  {value: 495, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '2311', provincecode: 23},
  {value: 496, label: 'ناحيه 1', district_pa: 'ناحيه 1', districtcode: '2312', provincecode: 23},
  {value: 497, label: 'ناحيه 2', district_pa: 'ناحيه 2', districtcode: '2313', provincecode: 23},
  {value: 498, label: 'ناحيه 3', district_pa: 'ناحيه 3', districtcode: '2314', provincecode: 23},
  {value: 499, label: 'ناحيه 4', district_pa: 'ناحيه 4', districtcode: '2315', provincecode: 23},
  {value: 500, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '3014', provincecode: 30},
  {value: 501, label: 'ناحيه 1', district_pa: 'ناحيه 1', districtcode: '3015', provincecode: 30},
  {value: 502, label: 'ناحيه 2', district_pa: 'ناحيه 2', districtcode: '3016', provincecode: 30},
  {value: 503, label: 'ناحيه 3', district_pa: 'ناحيه 3', districtcode: '3017', provincecode: 30},
  {value: 504, label: 'ناحيه 4', district_pa: 'ناحيه 4', districtcode: '3018', provincecode: 30},
  {value: 505, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '3217', provincecode: 32},
  {value: 506, label: 'ناحيه1', district_pa: 'ناحيه1', districtcode: '3218', provincecode: 32},
  {value: 507, label: 'ناحيه2', district_pa: 'ناحيه2', districtcode: '3219', provincecode: 32},
  {value: 508, label: 'ناحيه3', district_pa: 'ناحيه3', districtcode: '3220', provincecode: 32},
  {value: 509, label: 'ناحيه4', district_pa: 'ناحيه4', districtcode: '3221', provincecode: 32},
  {value: 510, label: 'ناحيه5', district_pa: 'ناحيه5', districtcode: '3222', provincecode: 32},
  {value: 511, label: 'ناحيه6', district_pa: 'ناحيه6', districtcode: '3223', provincecode: 32},
  {value: 512, label: 'ناحيه7', district_pa: 'ناحيه7', districtcode: '3224', provincecode: 32},
  {value: 513, label: 'ناحيه8', district_pa: 'ناحيه8', districtcode: '3225', provincecode: 32},
  {value: 514, label: 'ناحيه9', district_pa: 'ناحيه9', districtcode: '3226', provincecode: 32},
  {value: 515, label: 'ناحيه10', district_pa: 'ناحيه10', districtcode: '3227', provincecode: 32},
  {value: 516, label: 'ناحيه11', district_pa: 'ناحيه11', districtcode: '3228', provincecode: 32},
  {value: 517, label: 'ناحيه12', district_pa: 'ناحيه12', districtcode: '3229', provincecode: 32},
  {value: 518, label: 'ناحيه13', district_pa: 'ناحيه13', districtcode: '3230', provincecode: 32},
  {value: 519, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '2717', provincecode: 27},
  {value: 520, label: 'ناحيه 1', district_pa: 'ناحيه 1', districtcode: '2718', provincecode: 27},
  {value: 521, label: 'ناحيه 2', district_pa: 'ناحيه 2', districtcode: '2719', provincecode: 27},
  {value: 522, label: 'ناحيه 3', district_pa: 'ناحيه 3', districtcode: '2720', provincecode: 27},
  {value: 523, label: 'ناحيه 4', district_pa: 'ناحيه 4', districtcode: '2721', provincecode: 27},
  {value: 524, label: 'ناحيه 5', district_pa: 'ناحيه 5', districtcode: '2722', provincecode: 27},
  {value: 525, label: 'ناحيه 6', district_pa: 'ناحيه 6', districtcode: '2723', provincecode: 27},
  {value: 526, label: 'ناحيه 7', district_pa: 'ناحيه 7', districtcode: '2724', provincecode: 27},
  {value: 527, label: 'ناحيه 8', district_pa: 'ناحيه 8', districtcode: '2725', provincecode: 27},
  {value: 528, label: 'ناحيه 9', district_pa: 'ناحيه 9', districtcode: '2726', provincecode: 27},
  {
    value: 529,
    label: 'ناحيه 10',
    district_pa: 'ناحيه 10',
    districtcode: '2727',
    provincecode: 27,
  },
  {
    value: 530,
    label: 'ناحيه 11',
    district_pa: 'ناحيه 11',
    districtcode: '2728',
    provincecode: 27,
  },
  {
    value: 531,
    label: 'ناحيه 12',
    district_pa: 'ناحيه 12',
    districtcode: '2729',
    provincecode: 27,
  },
  {
    value: 532,
    label: 'ناحيه 13',
    district_pa: 'ناحيه 13',
    districtcode: '2730',
    provincecode: 27,
  },
  {
    value: 533,
    label: 'ناحيه 14',
    district_pa: 'ناحيه 14',
    districtcode: '2731',
    provincecode: 27,
  },
  {
    value: 534,
    label: 'ناحيه 15',
    district_pa: 'ناحيه 15',
    districtcode: '2732',
    provincecode: 27,
  },
  {
    value: 535,
    label: 'ناحيه 16',
    district_pa: 'ناحيه 16',
    districtcode: '2733',
    provincecode: 27,
  },
  {
    value: 536,
    label: 'ناحيه 17',
    district_pa: 'ناحيه 17',
    districtcode: '2734',
    provincecode: 27,
  },
  {
    value: 537,
    label: 'نا معلوم',
    district_pa: 'نا معلوم',
    districtcode: '0208',
    provincecode: 2,
  },
  {value: 538, label: 'ناحيه 1', district_pa: 'ناحيه 1', districtcode: '0209', provincecode: 2},
  {value: 539, label: 'ناحيه 2', district_pa: 'ناحيه 2', districtcode: '0210', provincecode: 2},
  {value: 540, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '1414', provincecode: 14},
  {value: 541, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '1516', provincecode: 15},
  {value: 542, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '1908', provincecode: 19},
  {value: 543, label: 'ناحيه 1', district_pa: 'ناحيه 1', districtcode: '1909', provincecode: 19},
  {value: 544, label: 'ناحيه 2', district_pa: 'ناحيه 2', districtcode: '1910', provincecode: 19},
  {value: 545, label: 'ناحيه 3', district_pa: 'ناحيه 3', districtcode: '1911', provincecode: 19},
  {value: 546, label: 'ناحيه 4', district_pa: 'ناحيه 4', districtcode: '1912', provincecode: 19},
  {value: 547, label: 'ناحيه 5', district_pa: 'ناحيه 5', districtcode: '1913', provincecode: 19},
  {value: 548, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '0706', provincecode: 7},
  {value: 549, label: 'ناحيه 1', district_pa: 'ناحيه 1', districtcode: '0707', provincecode: 7},
  {value: 550, label: 'ناحيه 2', district_pa: 'ناحيه 2', districtcode: '0708', provincecode: 7},
  {
    value: 551,
    label: 'نا معلوم',
    district_pa: 'نا معلوم',
    districtcode: '0508',
    provincecode: 5,
  },
  {value: 552, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '0623', provincecode: 6},
  {value: 553, label: 'ناحيه 1', district_pa: 'ناحيه 1', districtcode: '0624', provincecode: 6},
  {value: 554, label: 'ناحيه 2', district_pa: 'ناحيه 2', districtcode: '0625', provincecode: 6},
  {value: 555, label: 'ناحيه 3', district_pa: 'ناحيه 3', districtcode: '0626', provincecode: 6},
  {value: 556, label: 'ناحيه 4', district_pa: 'ناحيه 4', districtcode: '0627', provincecode: 6},
  {value: 557, label: 'ناحيه 5', district_pa: 'ناحيه 5', districtcode: '0628', provincecode: 6},
  {value: 558, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '3406', provincecode: 34},
  {value: 559, label: 'ناحيه 1', district_pa: 'ناحيه 1', districtcode: '3407', provincecode: 34},
  {value: 560, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '1220', provincecode: 12},
  {value: 561, label: 'میرزکه', district_pa: 'میرزکه', districtcode: '1312', provincecode: 13},
  {value: 562, label: 'آبشار', district_pa: 'آبشار', districtcode: '0808', provincecode: 8},
  {value: 563, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '0312', provincecode: 3},
  {value: 564, label: 'ناحيه 1', district_pa: 'ناحيه 1', districtcode: '0313', provincecode: 3},
  {value: 565, label: 'ناحيه 2', district_pa: 'ناحيه 2', districtcode: '0314', provincecode: 3},
  {value: 566, label: 'ناحيه 3', district_pa: 'ناحيه 3', districtcode: '0315', provincecode: 3},
  {value: 567, label: 'ناحيه 4', district_pa: 'ناحيه 4', districtcode: '0316', provincecode: 3},
  {value: 568, label: 'ناحيه 5', district_pa: 'ناحيه 5', districtcode: '0317', provincecode: 3},
  {value: 569, label: 'ناحيه 6', district_pa: 'ناحيه 6', districtcode: '0318', provincecode: 3},
  {value: 570, label: 'ناحيه 7', district_pa: 'ناحيه 7', districtcode: '0319', provincecode: 3},
  {value: 571, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '2009', provincecode: 20},
  {value: 572, label: 'ناحيه 1', district_pa: 'ناحيه 1', districtcode: '2010', provincecode: 20},
  {value: 573, label: 'ناحيه 2', district_pa: 'ناحيه 2', districtcode: '2011', provincecode: 20},
  {value: 574, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '2208', provincecode: 22},
  {value: 575, label: 'ناحيه 1', district_pa: 'ناحيه 1', districtcode: '2209', provincecode: 22},
  {value: 576, label: 'ناحيه 2', district_pa: 'ناحيه 2', districtcode: '2210', provincecode: 22},
  {value: 577, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '0410', provincecode: 4},
  {value: 578, label: 'نامعلوم', district_pa: 'نامعلوم', districtcode: '2612', provincecode: 26},
  {
    value: 579,
    label: 'جلال آباد',
    district_pa: 'جلال آباد',
    districtcode: '0629',
    provincecode: 6,
  },
  {value: 580, label: 'گرشک', district_pa: 'گرشک', districtcode: '3019', provincecode: 30},
  {value: 581, label: 'مارجه', district_pa: 'مارجه', districtcode: '3020', provincecode: 30},
  {value: 582, label: 'گيزاب', district_pa: 'گيزاب', districtcode: '2512', provincecode: 25},
  {
    value: 583,
    label: 'ناوه میش',
    district_pa: 'ناوه میش',
    districtcode: '2421',
    provincecode: 24,
  },
  {value: 584, label: 'ناحيه 6', district_pa: 'ناحيه 6', districtcode: '0631', provincecode: 6},
  {
    value: 585,
    label: 'ناوه میش',
    district_pa: 'ناوه میش',
    districtcode: '3021',
    provincecode: 30,
  },
  {
    value: 586,
    label: 'روحانی بابا',
    district_pa: 'روحانی بابا',
    districtcode: '1314',
    provincecode: 13,
  },
  {
    value: 587,
    label: 'گرده څیری',
    district_pa: 'گرده څیری',
    districtcode: '1315',
    provincecode: 13,
  },
  {value: 588, label: 'بادپښ', district_pa: 'بادپښ', districtcode: '0709', provincecode: 7},
  {value: 589, label: 'زاول', district_pa: 'زاول', districtcode: '3232', provincecode: 32},
  {value: 590, label: 'ناحيه14', district_pa: 'ناحيه14', districtcode: '3233', provincecode: 32},
  {value: 591, label: 'ناحيه15', district_pa: 'ناحيه15', districtcode: '3234', provincecode: 32},
  {value: 592, label: 'آقتاش', district_pa: 'آقتاش', districtcode: '1914', provincecode: 19},
  {
    value: 593,
    label: 'لجه منګل',
    district_pa: 'لجه منګل',
    districtcode: '1313',
    provincecode: 13,
  },
  {value: 594, label: 'تخته پل', district_pa: 'تخته پل', districtcode: '2736', provincecode: 27},
  {value: 595, label: 'چنارتو', district_pa: 'چنارتو', districtcode: '2513', provincecode: 25},
  {
    value: 596,
    label: 'ناحيه 10',
    district_pa: 'ناحيه 10',
    districtcode: '2128',
    provincecode: 21,
  },
  {value: 597, label: 'کوه زور', district_pa: 'کوه زور', districtcode: '3235', provincecode: 32},
]
