<?php

namespace Database\Seeders\auth_sys;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class PermissionSeeder extends Seeder
{
    public function run(): void
    {
        $permissions = [
            [
                'name' => 'company-list',
                'name_dr' => 'لیست کمپنی',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'company-create',
                'name_dr' => 'اضافه کردن کمپنی',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'company-edit',
                'name_dr' => 'تجدید کردن کمپنی',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'company-view',
                'name_dr' => 'نمایش کردن کمپنی',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'company-status',
                'name_dr' => 'تغیر حالت کمپنی',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'contract-list',
                'name_dr' => 'لیست قرارداد',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'contract-create',
                'name_dr' => 'اضافه کردن قرارداد',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'contract-edit',
                'name_dr' => 'تجدید کردن قرارداد',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'contract-view',
                'name_dr' => 'نمایش کردن قرارداد',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'contract-status',
                'name_dr' => 'تغیر حالت قرارداد',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'bosse-list',
                'name_dr' => 'لیست ریّس',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'bosse-create',
                'name_dr' => 'اضافه کردن ریّس',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'bosse-edit',
                'name_dr' => 'تجدید کردن ریّس',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'bosse-view',
                'name_dr' => 'نمایش کردن ریّس',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'bosse-status',
                'name_dr' => 'تغیر حالت ریّس',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'assistant-list',
                'name_dr' => 'لیست معاونین',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'assistant-create',
                'name_dr' => 'اضافه کردن معاونین',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'assistant-edit',
                'name_dr' => 'تجدید کردن معاونین',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'assistant-view',
                'name_dr' => 'نمایش کردن معاونین',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'assistant-status',
                'name_dr' => 'تغیر حالت معاونین',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'license-list',
                'name_dr' => 'لیست جواز ',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'license-create',
                'name_dr' => 'اضافه کردن جواز ',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'license-edit',
                'name_dr' => 'تجدید کردن جواز ',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'license-view',
                'name_dr' => 'نمایش کردن جواز ',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'license-status',
                'name_dr' => 'تغیر حالت جواز ',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'employee-list',
                'name_dr' => 'لیست کارمند',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'employee-create',
                'name_dr' => 'اضافه کردن کارمند',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'employee-edit',
                'name_dr' => 'تجدید کردن کارمند',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'employee-view',
                'name_dr' => 'نمایش کردن کارمند',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'employee-status',
                'name_dr' => 'تغیر حالت کارمند',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'weapon-list',
                'name_dr' => 'لیست سلاح  ',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'weapon-create',
                'name_dr' => 'اضافه کردن سلاح  ',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'weapon-edit',
                'name_dr' => 'تجدید کردن سلاح  ',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'weapon-view',
                'name_dr' => 'نمایش کردن سلاح  ',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'weapon-status',
                'name_dr' => 'تغیر حالت سلاح  ',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'vehical-list',
                'name_dr' => 'لیست وسایط',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'vehical-create',
                'name_dr' => 'اضافه کردن وسایط',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'vehical-edit',
                'name_dr' => 'تجدید کردن وسایط',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'vehical-view',
                'name_dr' => 'نمایش کردن وسایط',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'vehical-status',
                'name_dr' => 'تغیر حالت وسایط',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'gun-list',
                'name_dr' => 'لیست سلاح در جدول',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'gun-create',
                'name_dr' => ' اضافه کردن سلاح در جدول',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'gun-edit',
                'name_dr' => 'تجدید کردن سلاح در جدول',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'cards',
                'name_dr' => 'کارت های چاپ شده',
                'guard_name' => 'web',
                'system_id' => 1,
            ],
            [
                'name' => 'workshop-company-list',
                'name_dr' => 'لیست کمپنی ها',
                'guard_name' => 'web',
                'system_id' => 2,
            ],
            [
                'name' => 'workshop-company-create',
                'name_dr' => 'اضافه کردن کمپنی',
                'guard_name' => 'web',
                'system_id' => 2,
            ],
            [
                'name' => 'workshop-company-view',
                'name_dr' => 'نمایش کردن کمپنی',
                'guard_name' => 'web',
                'system_id' => 2,
            ],
            [
                'name' => 'workshop-company-edit',
                'name_dr' => 'تجدید کردن کمپنی',
                'guard_name' => 'web',
                'system_id' => 2,
            ],
            [
                'name' => 'workshop-company-status',
                'name_dr' => 'تغیر حالت کمپنی',
                'guard_name' => 'web',
                'system_id' => 2,
            ],
            [
                'name' => 'workshop-boss-list',
                'name_dr' => 'لیست ریس ها',
                'guard_name' => 'web',
                'system_id' => 2,
            ],
            [
                'name' => 'workshop-boss-create',
                'name_dr' => 'اضافه کردن ریس',
                'guard_name' => 'web',
                'system_id' => 2,
            ],
            [
                'name' => 'workshop-boss-view',
                'name_dr' => 'نمایش کردن ریس',
                'guard_name' => 'web',
                'system_id' => 2,
            ],
            [
                'name' => 'workshop-boss-edit',
                'name_dr' => 'تجدید کردن ریس',
                'guard_name' => 'web',
                'system_id' => 2,
            ],
            [
                'name' => 'workshop-assistant-list',
                'name_dr' => 'لیست معاون ها',
                'guard_name' => 'web',
                'system_id' => 2,
            ],
            [
                'name' => 'workshop-assistant-create',
                'name_dr' => 'اضافه کردن معاون',
                'guard_name' => 'web',
                'system_id' => 2,
            ],
            [
                'name' => 'workshop-assistant-view',
                'name_dr' => 'نمایش کردن معاون',
                'guard_name' => 'web',
                'system_id' => 2,
            ],
            [
                'name' => 'workshop-assistant-edit',
                'name_dr' => 'تجدید کردن معاون',
                'guard_name' => 'web',
                'system_id' => 2,
            ],
            [
                'name' => 'workshop-license-list',
                'name_dr' => 'لیست جواز ها',
                'guard_name' => 'web',
                'system_id' => 2,
            ],
            [
                'name' => 'workshop-license-create',
                'name_dr' => 'اضافه کردن جواز',
                'guard_name' => 'web',
                'system_id' => 2,
            ],
            [
                'name' => 'workshop-license-view',
                'name_dr' => 'نمایش کردن جواز',
                'guard_name' => 'web',
                'system_id' => 2,
            ],
            [
                'name' => 'workshop-license-edit',
                'name_dr' => 'تجدید کردن جواز',
                'guard_name' => 'web',
                'system_id' => 2,
            ],
            [
                'name' => 'workshop-license-send',
                'name_dr' => 'ارسال جواز به چاپ',
                'guard_name' => 'web',
                'system_id' => 2,
            ],
            [
                'name' => 'workshop-print-list',
                'name_dr' => 'لیست کارت ها',
                'guard_name' => 'web',
                'system_id' => 2,
            ],
            [
                'name' => 'workshop-print-accept',
                'name_dr' => 'تایید کارت',
                'guard_name' => 'web',
                'system_id' => 2,
            ],
            [
                'name' => 'workshop-print-card',
                'name_dr' => 'چاپ کارت',
                'guard_name' => 'web',
                'system_id' => 2,
            ],
            [
                'name' => 'workshop-print-card-view',
                'name_dr' => 'نمایش تمام معلومات کارت',
                'guard_name' => 'web',
                'system_id' => 2,
            ],
            // System User Managment Permissions
            [
                'name' => 'user-create',
                'name_dr' => 'ثبت کاربر',
                'guard_name' => 'web',
                'system_id' => 6,
            ],
            [
                'name' => 'user-list',
                'name_dr' => 'لیست کاربر',
                'guard_name' => 'web',
                'system_id' => 6,
            ],
            [
                'name' => 'user-edit',
                'name_dr' => 'تجدید کاربر',
                'guard_name' => 'web',
                'system_id' => 6,
            ],
            [
                'name' => 'user-destroy',
                'name_dr' => 'حذف کاربر',
                'guard_name' => 'web',
                'system_id' => 6,
            ],
            [
                'name' => 'role-create',
                'name_dr' => 'ثبت صلاحیت',
                'guard_name' => 'web',
                'system_id' => 6,
            ],
            [
                'name' => 'role-list',
                'name_dr' => 'لیست صلاحیت',
                'guard_name' => 'web',
                'system_id' => 6,
            ],
            [
                'name' => 'role-edit',
                'name_dr' => 'تجدید صلاحیت',
                'guard_name' => 'web',
                'system_id' => 6,
            ],
            [
                'name' => 'admin-create',
                'name_dr' => 'ثبت سوپروایزر',
                'guard_name' => 'web',
                'system_id' => 6,
            ],
            [
                'name' => 'admin-edit',
                'name_dr' => 'تجدید سوپروایزر',
                'guard_name' => 'web',
                'system_id' => 6,
            ],
            [
                'name' => 'admin-view',
                'name_dr' => 'دیدن سوپروایزر',
                'guard_name' => 'web',
                'system_id' => 6,
            ],
            [
                'name' => 'department-view',
                'name_dr' => 'دیدن مدیریت',
                'guard_name' => 'web',
                'system_id' => 6,
            ],
            [
                'name' => 'department-all-view',
                'name_dr' => 'دیدن همه مدیریت',
                'guard_name' => 'web',
                'system_id' => 6,
            ],
            [
                'name' => 'all-view',
                'name_dr' => 'دیدن همه ریکارد ها',
                'guard_name' => 'web',
                'system_id' => 6,
            ],
            [
                'name' => 'province-view',
                'name_dr' => 'دیدن ریکارد های ولایت',
                'guard_name' => 'web',
                'system_id' => 6,
            ],
            [
                'name' => 'view',
                'name_dr' => 'دیدن',
                'guard_name' => 'web',
                'system_id' => 6,
            ],
            [
                'name' => 'system-report',
                'name_dr' => 'راپور سیستم',
                'guard_name' => 'web',
                'system_id' => 6,
            ],
            // K9 System Permissions
            [
                'name' => 'k9-company-list',
                'name_dr' => 'لیست کمپنی ها',
                'guard_name' => 'web',
                'system_id' => 4,
            ],
            [
                'name' => 'k9-company-create',
                'name_dr' => 'اضافه کردن کمپنی',
                'guard_name' => 'web',
                'system_id' => 4,
            ],
            [
                'name' => 'k9-company-view',
                'name_dr' => 'نمایش کردن کمپنی',
                'guard_name' => 'web',
                'system_id' => 4,
            ],
            [
                'name' => 'k9-company-edit',
                'name_dr' => 'تجدید کردن کمپنی',
                'guard_name' => 'web',
                'system_id' => 4,
            ],
            [
                'name' => 'k9-boss-list',
                'name_dr' => 'لیست ریس ها',
                'guard_name' => 'web',
                'system_id' => 4,
            ],
            [
                'name' => 'k9-boss-create',
                'name_dr' => 'اضافه کردن ریس',
                'guard_name' => 'web',
                'system_id' => 4,
            ],
            [
                'name' => 'k9-boss-view',
                'name_dr' => 'نمایش کردن ریس',
                'guard_name' => 'web',
                'system_id' => 4,
            ],
            [
                'name' => 'k9-boss-edit',
                'name_dr' => 'تجدید کردن ریس',
                'guard_name' => 'web',
                'system_id' => 4,
            ],
            [
                'name' => 'k9-assistant-list',
                'name_dr' => 'لیست معاون ها',
                'guard_name' => 'web',
                'system_id' => 4,
            ],
            [
                'name' => 'k9-assistant-create',
                'name_dr' => 'اضافه کردن معاون',
                'guard_name' => 'web',
                'system_id' => 4,
            ],
            [
                'name' => 'k9-assistant-view',
                'name_dr' => 'نمایش کردن معاون',
                'guard_name' => 'web',
                'system_id' => 4,
            ],
            [
                'name' => 'k9-assistant-edit',
                'name_dr' => 'تجدید کردن معاون',
                'guard_name' => 'web',
                'system_id' => 4,
            ],
            // Drone Cameras Permissions
            [
                'name' => 'drone-company-list',
                'name_dr' => 'لیست کمپنی ها',
                'guard_name' => 'web',
                'system_id' => 5,
            ],
            [
                'name' => 'drone-company-create',
                'name_dr' => 'اضافه کردن کمپنی',
                'guard_name' => 'web',
                'system_id' => 5,
            ],
            [
                'name' => 'drone-personnel-create',
                'name_dr' => 'اضافه کردن استفاده کننده شخصی',
                'guard_name' => 'web',
                'system_id' => 5,
            ],
            [
                'name' => 'drone-personnel-license-create',
                'name_dr' => 'اضافه کردن جواز استفاده کننده شخصی',
                'guard_name' => 'web',
                'system_id' => 5,
            ],
            [
                'name' => 'drone-personnel-license-edit',
                'name_dr' => 'تجدید کردن جواز استفاده کننده شخصی',
                'guard_name' => 'web',
                'system_id' => 5,
            ],
            [
                'name' => 'drone-personnel-license-view',
                'name_dr' => 'نمایش کردن جواز استفاده کننده شخصی',
                'guard_name' => 'web',
                'system_id' => 5,
            ],
            [
                'name' => 'drone-personnel-license-send',
                'name_dr' => 'ارسال جواز استفاده کننده شخصی',
                'guard_name' => 'web',
                'system_id' => 5,
            ],
            [
                'name' => 'drone-company-view',
                'name_dr' => 'نمایش کردن کمپنی',
                'guard_name' => 'web',
                'system_id' => 5,
            ],
            [
                'name' => 'drone-company-edit',
                'name_dr' => 'تجدید کردن کمپنی',
                'guard_name' => 'web',
                'system_id' => 5,
            ],
            [
                'name' => 'drone-company-status',
                'name_dr' => 'تغیر حالت کمپنی',
                'guard_name' => 'web',
                'system_id' => 5,
            ],
            [
                'name' => 'drone-boss-list',
                'name_dr' => 'لیست ریس ها',
                'guard_name' => 'web',
                'system_id' => 5,
            ],
            [
                'name' => 'drone-boss-create',
                'name_dr' => 'اضافه کردن ریس',
                'guard_name' => 'web',
                'system_id' => 5,
            ],
            [
                'name' => 'drone-boss-view',
                'name_dr' => 'نمایش کردن ریس',
                'guard_name' => 'web',
                'system_id' => 5,
            ],
            [
                'name' => 'drone-boss-edit',
                'name_dr' => 'تجدید کردن ریس',
                'guard_name' => 'web',
                'system_id' => 5,
            ],
            [
                'name' => 'drone-assistant-list',
                'name_dr' => 'لیست معاون ها',
                'guard_name' => 'web',
                'system_id' => 5,
            ],
            [
                'name' => 'drone-assistant-create',
                'name_dr' => 'اضافه کردن معاون',
                'guard_name' => 'web',
                'system_id' => 5,
            ],
            [
                'name' => 'drone-assistant-view',
                'name_dr' => 'نمایش کردن معاون',
                'guard_name' => 'web',
                'system_id' => 5,
            ],
            [
                'name' => 'drone-assistant-edit',
                'name_dr' => 'تجدید کردن معاون',
                'guard_name' => 'web',
                'system_id' => 5,
            ],
            [
                'name' => 'drone-license-list',
                'name_dr' => 'لیست جواز ها',
                'guard_name' => 'web',
                'system_id' => 5,
            ],
            [
                'name' => 'drone-license-create',
                'name_dr' => 'اضافه کردن جواز',
                'guard_name' => 'web',
                'system_id' => 5,
            ],
            [
                'name' => 'drone-license-view',
                'name_dr' => 'نمایش کردن جواز',
                'guard_name' => 'web',
                'system_id' => 5,
            ],
            [
                'name' => 'drone-license-edit',
                'name_dr' => 'تجدید کردن جواز',
                'guard_name' => 'web',
                'system_id' => 5,
            ],
            [
                'name' => 'drone-license-send',
                'name_dr' => 'ارسال جواز به چاپ',
                'guard_name' => 'web',
                'system_id' => 5,
            ],
            [
                'name' => 'drone-print-list',
                'name_dr' => 'لیست کارت ها',
                'guard_name' => 'web',
                'system_id' => 5,
            ],
            [
                'name' => 'drone-print-accept',
                'name_dr' => 'تایید کارت',
                'guard_name' => 'web',
                'system_id' => 5,
            ],
            [
                'name' => 'drone-print-card',
                'name_dr' => 'چاپ کارت',
                'guard_name' => 'web',
                'system_id' => 5,
            ],
            [
                'name' => 'drone-print-card-view',
                'name_dr' => 'نمایش تمام معلومات کارت',
                'guard_name' => 'web',
                'system_id' => 5,
            ],
            // GPS System Permissions
            [
                'name' => 'gps-company-list',
                'name_dr' => 'لیست کمپنی ها',
                'guard_name' => 'web',
                'system_id' => 3,
            ],
            [
                'name' => 'gps-company-create',
                'name_dr' => 'اضافه کردن کمپنی',
                'guard_name' => 'web',
                'system_id' => 3,
            ],
            [
                'name' => 'gps-company-view',
                'name_dr' => 'نمایش کردن کمپنی',
                'guard_name' => 'web',
                'system_id' => 3,
            ],
            [
                'name' => 'gps-company-edit',
                'name_dr' => 'تجدید کردن کمپنی',
                'guard_name' => 'web',
                'system_id' => 3,
            ],
            [
                'name' => 'gps-company-status',
                'name_dr' => 'تغیر حالت کمپنی',
                'guard_name' => 'web',
                'system_id' => 3,
            ],
            [
                'name' => 'gps-boss-list',
                'name_dr' => 'لیست ریس ها',
                'guard_name' => 'web',
                'system_id' => 3,
            ],
            [
                'name' => 'gps-boss-create',
                'name_dr' => 'اضافه کردن ریس',
                'guard_name' => 'web',
                'system_id' => 3,
            ],
            [
                'name' => 'gps-boss-view',
                'name_dr' => 'نمایش کردن ریس',
                'guard_name' => 'web',
                'system_id' => 3,
            ],
            [
                'name' => 'gps-boss-edit',
                'name_dr' => 'تجدید کردن ریس',
                'guard_name' => 'web',
                'system_id' => 3,
            ],
            [
                'name' => 'gps-assistant-list',
                'name_dr' => 'لیست معاون ها',
                'guard_name' => 'web',
                'system_id' => 3,
            ],
            [
                'name' => 'gps-assistant-create',
                'name_dr' => 'اضافه کردن معاون',
                'guard_name' => 'web',
                'system_id' => 3,
            ],
            [
                'name' => 'gps-assistant-view',
                'name_dr' => 'نمایش کردن معاون',
                'guard_name' => 'web',
                'system_id' => 3,
            ],
            [
                'name' => 'gps-assistant-edit',
                'name_dr' => 'تجدید کردن معاون',
                'guard_name' => 'web',
                'system_id' => 3,
            ],
            [
                'name' => 'gps-license-list',
                'name_dr' => 'لیست جواز ها',
                'guard_name' => 'web',
                'system_id' => 3,
            ],
            [
                'name' => 'gps-license-create',
                'name_dr' => 'اضافه کردن جواز',
                'guard_name' => 'web',
                'system_id' => 3,
            ],
            [
                'name' => 'gps-license-view',
                'name_dr' => 'نمایش کردن جواز',
                'guard_name' => 'web',
                'system_id' => 3,
            ],
            [
                'name' => 'gps-license-edit',
                'name_dr' => 'تجدید کردن جواز',
                'guard_name' => 'web',
                'system_id' => 3,
            ],
            [
                'name' => 'gps-license-send',
                'name_dr' => 'ارسال جواز به چاپ',
                'guard_name' => 'web',
                'system_id' => 3,
            ],
            [
                'name' => 'gps-print-list',
                'name_dr' => 'لیست کارت ها',
                'guard_name' => 'web',
                'system_id' => 3,
            ],
            [
                'name' => 'gps-print-accept',
                'name_dr' => 'تایید کارت',
                'guard_name' => 'web',
                'system_id' => 3,
            ],
            [
                'name' => 'gps-print-card',
                'name_dr' => 'چاپ کارت',
                'guard_name' => 'web',
                'system_id' => 3,
            ],
            [
                'name' => 'gps-print-card-view',
                'name_dr' => 'نمایش تمام معلومات کارت',
                'guard_name' => 'web',
                'system_id' => 3,
            ],

        ];

        foreach ($permissions as $permission) {
            Permission::create($permission);
        }
    }
}
